default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: hood_link
  password:

development:
  <<: *default
  database: hood_link

test: &test
  <<: *default
  database: hood_link_test